var GAME_LEVELS = [
    [
        "                                                                                ",
        "                                                                                ",
        "                                                                                ",
        "                                                                                ",
        "                                                                                ",
        "                                                                                ",
        "                                  v                              xxxxx          ",
        "                                                                 xx!xx          ",
        "                                                                 x!!!x          ",
        "                                                                 xx!xx          ",
        "                                                                  xvx           ",
        "                                                                                ",
        "  xx                                                                            ",
        "  x                       o o                                                   ",
        "  x                                                                             ",
        "  x           o        xxxxxxxx                                                 ",
        "  x  @     d      xxxxxx     xxxxx      d    o                 xxx o x          ",
        "  xxxxxxxxxxxxxxxxx          x!      xxxxxxx                 xxxxx o x          ",
        "                             x!    o !x    xxxx         o        x o x          ",
        "                             x!      !x                          x o x          ",
        "                             x!    xxxx                          x o x          ",
        "                             x!      !x          xx    xxxx      x o xxxxx      ",
        "                             x!      !x                          x o     x      ",
        "                             x!xxx   !x           oooo         xxx     o x      ",
        "                             x! o    !x                     xxxxxx       x      ",
        "                             x!      !x       xxxxxxxxxxxxxxx     xxxxxxxx      ",
        "                             xxxxxxxxxx       !!!!!!!!!!!!!!!     xxxxxxxx      ",
        "                                                                                ",
        "                                                                                "
    ], [
        "                                                                                                              ",
        "                                                                                                              ",
        "                                                                                                              ",
        "                                                                                                              ",
        "                  vvvvvv                                                                                      ",
        "                                                                                                              ",
        "                                                                                                              ",
        "                                                                                     xxxxxxxxxxxvxxxxxxxx     ",
        "                                                                                     x                  x     ",
        "                                                                                     x                  x     ",
        "                                                                                     x o                x     ",
        "                                                              d                      x                  x     ",
        "                                                   xxxxxx!!xxxx                      xxxxxxxxxx         x     ",
        "                        xxxxxxxxxxxxxxxxxxxx            x!!x                                         xxxx     ",
        "                        x                               x!!x                                                  ",
        "       o o o o o        x                         xxxxxxx!!x                                 xxx              ",
        "  =  @                  x                      o        x!!x      o    xxxx                             x     ",
        "  xxxxxxxxxxxxxxxx   o                                  x!!x =         x                                x     ",
        "                             o                 xx       x!!xxxxxxxxx     o o                            x     ",
        "                  xxxxxx            xx=        xx       x!!x                        xxxxxxxxxxxxxxxxxxxxx     ",
        "                       xxxxxxxxxx!!!xxxxxxxxxxxxx       xxxx      xxxxxxxxxxxxx!!!!!x                         ",
        "                                x!!!x                                         x!!!!!x                         ",
        "                                xxxxx                                         x!!!!!x                         ",
        "                                                                              x!!!!!x                         ",
        "                                                                              xxxxxxx                         ",
        "                                                                                                              ",
        "                                                                                                              ",
        "                                                                                                              ",
        "                                                                                                              ",
        "                                                                                                              ",
        "                                                                                                              ",
        "                                                                                                              "
    ],
    [
        "                                                                                                              ",
        " xxxxxxxxxxxxxxxxxx                                                                                           ",
        "                                                                                                              ",
        "                                                                                                              ",
        "   @                                                                                                          ",
        "  xxxxxxxxxxxxxxxxx                          x                                                                ",
        "                  x                          x                                                                ",
        "                 x=       o                  x    xxxxxx                                                      ",
        "                  x                          x                                                                ",
        "                  x     xxxx                 x                                                                ",
        "                 x=                          x                                                                ",
        "                  x                          x                      d                                         ",
        "                  xxxxxxxxxxxxx              x                  xxxxxxxxxxx                                   ",
        "                              x         o    x                            x! o                                ",
        "                             x=              x                            x!  o                               ",
        "                              x        xxxx  x                            x! o                                ",
        "                             x=              x            xxxxxxx         x!  o                               ",
        "                              x                                           x! o                                ",
        "                              x                                           x!  o                         x     ",
        "                              xxxxxxxxxxxxxxxx                      xxxxxxx! o                      o   x     ",
        "                                            x=                            x!  o                     o   x     ",
        "                                             x    o  o   o  o             x! o                     o o  x     ",
        "                                            x=                    xx      x!  o                 d       x     ",
        "                                             x   o  o  o  o  o  o         x!      xxxxxxx!!!!xxxxxxxxxxxx     ",
        "                                             x                            x       x     x!!!!x                ",
        "                                             xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x   x     x!!!!x                ",
        "                                                                          x!!!x!!!x     x!!!!x                ",
        "                                                                                        xxxxxx                ",
        "                                                                                                              ",
        "                                                                                                              ",
        "                                                                                                              "
    ]
];

if (typeof module != "undefined" && module.exports)
    module.exports = GAME_LEVELS;